### ISSUE TITLE
Questions about multiple sites, stripping out styles, and the sidebar.

### ISSUE THREAD

**Issue by leoj3n** [bit-docs/bit-docs#13]
@justinbmeyer Asked me to take a look into the bit-docs org, and this repo, to see about continuing the vision. However, that vision is not entirely clear, and I have some questions. Justin is unusually busy this week, so I'm writing down my thoughts and questions to be answered when he has time.

## Multiple Sites

The [documentjs.json](https://github.com/bit-docs/bit-docs/blob/master/documentjs.json) file in this bit-docs repo's root comes from the original [DocumentJS](https://github.com/bitovi/documentjs/blob/major/documentjs.json) project, and contains directives to configure building multiple "sites".

In comparison, it looks like the new bit-docs site configuration syntax isn't geared towards this "multiple sites" paradigm. Is that correct? Here is my hack in `package.json` to build the main docs in addition to the `multi` example (see glob pattern):

```
  "bit-docs": {
    "dependencies": {
      "bit-docs-glob-finder": "^0.0.5",
      "bit-docs-dev": "^0.0.3",
      "bit-docs-js": "^0.0.6",
      "bit-docs-tag-sourceref": "^0.0.3",
      "bit-docs-generate-html": "^0.3.0",
      "bit-docs-html-canjs": "^0.3.19",
      "bit-docs-prettify": "^0.1.0",
      "bit-docs-html-highlight-line": "^0.2.2",
      "bit-docs-tag-demo": "^0.3.0",
      "bit-docs-tag-package": "^0.0.3"
    },
    "glob": {
      "pattern": "{docs,examples/multi}/**/*.{js,md}"
    },
    "parent": "DocumentJS",
    "minifyBuild": false
  },
```

With this config, running the command:

```
./bin/bit-docs
```

Generates the output:

```
doing this for  DocumentJS.projectConfig
doing this for  DocumentJS.siteConfig
doing this for  DocumentJS.siteConfig
doing this for  DocumentJS.siteConfig
doing this for  multi/lib/graph.graphData
doing this for  multi/lib/graph
```

Using `http-server` and visiting <http://127.0.0.1:8080/doc/> looks like this:

![image](https://cloud.githubusercontent.com/assets/990216/23881666/e2fedb64-0829-11e7-84ef-f64d324be1c3.png)

(Note: The sidebar navigation doesn't work)

To see the `multi` example site I have to change the URL to <http://127.0.0.1:8080/doc/multi.html>:

![image](https://cloud.githubusercontent.com/assets/990216/23881715/3e14c6e4-082a-11e7-9a81-57bcebf1a77e.png)

Is there going to be a way to have multiple configs **[as has been possible](https://github.com/bitovi/documentcss/blob/master/Gruntfile.js#L8-L46)** with DocumentJS, Or is the nature of this repo changing in that sense? Looking at the CanJS and StealJS repos that are making use of this `bit-docs/bit-docs` repo, in tandem with the org's configurable plugins, it looks like they are doing basically what I have done above. Are they manually configuring the navigation between the various pages? Sorry if the answer is obvious somewhere, but I haven't crawled through the code in those repositories yet (was still getting my bearings in this repo today).

## Stripping out Styles

Justin mentioned making this as barebones as possible, a.k.a ripping out all the styles.

Sounds good to me, but can you comment on how this fits in with the new vision of this repo? I'm trying to better understand how this tool will eventually look like and be used, compared to DocumentJS.

## Building the Sidebar Functionality

Justin wants something to do with a sidebar. I think this needs to be done in a HTML generator. Two files Justin mentioned while quickly going over the needed sidebar functionality:

- https://github.com/bit-docs/bit-docs-generate-html
- https://github.com/canjs/bit-docs-html-canjs

To try and understand things better, I tried going through the commit history starting from the time this repo was forked from DocumentJS, but there is too much to go through, at least for today.

**Comment by leoj3n** [comment]
https://github.com/bit-docs/bit-docs-generate-html/commit/3f41f524eb18cc8f7497f28b4254b12682d40296

**Comment by leoj3n** [comment]
`https://github.com/canjs/bit-docs-html-canjs/pull/219`

**Comment by justinbmeyer** [comment]
> In comparison, it looks like the new bit-docs site configuration syntax isn't geared towards this "multiple sites" paradigm. 

Yes, bit-docs doesn't currently support multiple versions.

-----------

> Sounds good to me, but can you comment on how this fits in with the new vision of this repo?

Yeah, I don't undestand wh the generated documentation shown above has so many styles. It should be practically devoid of any styling.  It isn't including the `canjs` theme are is it?

![cursor_and_questions_about_multiple_sites__stripping_out_styles__and_the_sidebar__ _issue__13_ _bit-docs_bit-docs](https://cloud.githubusercontent.com/assets/78602/23930746/4a464c3a-08fc-11e7-88c5-f269ec1cf9af.png)

`bit-docs` itself shouldn't include any styles.  `bit-docs` as a repo should be independent of its generated docs.  This is similar to how `stealjs/stealjs` "builds" the docs from `stealjs/steal` and `stealjs/steal-tools`

**Comment by leoj3n** [comment]
Great thanks that clears a lot up. The separation is how I thought it
should work too, but didn't know for sure because it wasn't explicitly
stated anywhere that I saw. So yeah will definitely document that intended
use, and look into those styles. I think that's the master branch not your
"doced" branch, maybe it's removed it there.

**Comment by leoj3n** [comment]
Update/dump:

## About the styling seen in the screenshots

The `master` branch had `bit-docs-html-canjs` in the `package.json` which apparently was the culprit for the styling seen in the OP screenshots. Removing the `bit-docs-html-canjs` plugin successfully kills the styling:

![image](https://cloud.githubusercontent.com/assets/990216/23971764/412d2fa0-099d-11e7-93b7-6d3ddbd45a8c.png)

Also in the OP, I had presented this wrong glob pattern (sorry for any confusion):

```
"pattern": "examples/multi/**/*.{js,md}"
```

I have edited the OP to have the correct pattern that I was actually talking about (that acts upon multiple directories at once):

```
"pattern": "{docs,examples/multi}/**/*.{js,md}"
```

For reference, here is what the generated docs look like with Justin's [`bit-docs-bit-doced`](https://github.com/bit-docs/bit-docs/tree/bit-docs-bit-doced) branch (that branch is quite a few changes ahead of `master`, including removing `bit-docs-html-canjs` and all the old DocumentJS documentation from `docs`):

![image](https://cloud.githubusercontent.com/assets/990216/23972086/7b1b876a-099e-11e7-859b-7b41d7a8658a.png)

## More Qs: Regarding declaration of dependencies

Currently, the `bit-docs-bit-doced` branch's `package.json` has `devDependencies` and `bit-docs` like:

```
  "devDependencies": {
    "bit-docs-glob-finder": "0.0.6",
    "connect": "^2.14.4",
    "mocha": ">= 1.18.0",
    "qunit-mocha-ui": "*",
    "rimraf": "2.1"
  },
  "bit-docs": {
    "dependencies": {
      "bit-docs-glob-finder": "^0.0.5",
      "bit-docs-dev": "^0.0.3",
      "bit-docs-js": "^0.0.6",
      "bit-docs-tag-sourceref": "^0.0.3",
      "bit-docs-generate-html": "^0.4.0",
      "bit-docs-prettify": "^0.1.1",
      "bit-docs-html-highlight-line": "^0.2.2"
    },
    "glob": {
      "pattern": "{node_modules/bit-docs-*,docs}/**/*.{js,md}"
    },
    "parent": "BitDocs",
    "minifyBuild": false
  }
```

After running `npm install`, the `node_modules` directory contains these items of interest:

```
node_modules
├── ...
├── bit-docs-glob-finder
├── bit-docs-process-tags
├── bit-docs-type-annotate
├── ...
├── glob
└── ...
```

After running `./bin/bit-docs`, the `lib/configure/node_modules/` directory contains:

```
lib/configure/node_modules/
├── ...
├── bit-docs-dev
├── bit-docs-generate-html
├── bit-docs-glob-finder
├── bit-docs-html-highlight-line
├── bit-docs-js
├── bit-docs-prettify
├── bit-docs-process-tags
├── bit-docs-tag-sourceref
├── bit-docs-type-annotate
├── ...
├── glob
├── ...
├── xtend
├── y18n
├── yargs
└── yargs-parser
```

Where the `...` are over ~300 packages.

I don't yet fully understand why the `bit-docs-glob-finder` package is defined in both `devDependencies` and `bit-docs.dependencies`.

Is this on purpose, and necessary? If so, Why?

**Comment by leoj3n** [comment]
## More Qs: Regarding declaration of dependencies

Currently, the `bit-docs-bit-doced` branch's `package.json` has `devDependencies` and `bit-docs` like:

```
  "devDependencies": {
    "bit-docs-glob-finder": "0.0.6",
    "connect": "^2.14.4",
    "mocha": ">= 1.18.0",
    "qunit-mocha-ui": "*",
    "rimraf": "2.1"
  },
  "bit-docs": {
    "dependencies": {
      "bit-docs-glob-finder": "^0.0.5",
      "bit-docs-dev": "^0.0.3",
      "bit-docs-js": "^0.0.6",
      "bit-docs-tag-sourceref": "^0.0.3",
      "bit-docs-generate-html": "^0.4.0",
      "bit-docs-prettify": "^0.1.1",
      "bit-docs-html-highlight-line": "^0.2.2"
    },
    "glob": {
      "pattern": "{node_modules/bit-docs-*,docs}/**/*.{js,md}"
    },
    "parent": "BitDocs",
    "minifyBuild": false
  }
```

After running `npm install`, the `node_modules` directory contains these items of interest:

```
node_modules
├── ...
├── bit-docs-glob-finder
├── bit-docs-process-tags
├── bit-docs-type-annotate
├── ...
├── glob
└── ...
```

After running `./bin/bit-docs`, the `lib/configure/node_modules/` directory contains:

```
lib/configure/node_modules/
├── ...
├── bit-docs-dev
├── bit-docs-generate-html
├── bit-docs-glob-finder
├── bit-docs-html-highlight-line
├── bit-docs-js
├── bit-docs-prettify
├── bit-docs-process-tags
├── bit-docs-tag-sourceref
├── bit-docs-type-annotate
├── ...
├── glob
├── ...
├── xtend
├── y18n
├── yargs
└── yargs-parser
```

Where the `...` are over ~300 packages.

I don't yet fully understand why the `bit-docs-glob-finder` package is defined in both `devDependencies` and `bit-docs.dependencies`.

Is this on purpose, and necessary? If so, Why?

**Comment by leoj3n** [comment]
If I remove `bit-docs-glob-finder` from `devDependencies`:

```
~/bit-docs bit-docs-bit-doced*
❯ ./bin/bit-docs -f
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-process-tags
WARNING!!
There is no @tag tag. did you mean @page ?
```

If I don't remove `bit-docs-glob-finder` from `devDependencies`:

```
~/bit-docs bit-docs-bit-doced
❯ ./bin/bit-docs -f
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-glob-finder/
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-process-tags
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-glob-finder/
WARNING!!
There is no @tag tag. did you mean @page ?

WARNING: Unable to document  {"src":{"line":41,"codeLine":61,"path":"node_modul
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-glob-finder/
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-glob-finder/
WARNING: Unable to document  {"src":{"line":798,"codeLine":798,"path":"node_mod
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-glob-finder/
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-glob-finder/
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-glob-finder/
WARNING: Unable to document  {"src":{"path":"node_modules/bit-docs-glob-finder/
```

**Comment by leoj3n** [comment]
The following was tested against `bit-docs@0.0.7`.

Error that happens if you remove `bit-docs-glob-finder`:

```
~/tmp/repro-bit-docs/super-simple-bit-docs master*
❯ ./node_modules/bit-docs/bin/bit-docs -f
/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:155
                throw e;
                ^

TypeError: siteConfig.finder is not a function
    at generateOne (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/generate/generate.js:49:36)
    at generateAndWatch (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/generate/generate.js:82:10)
    at /Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/main.js:6:10
    at _fulfilled (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:796:13)
    at /Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:604:44
    at runSingle (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:137:13)
    at flush (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

---

Error that happens if you remove `bit-docs-dev`:

```
~/tmp/repro-bit-docs/super-simple-bit-docs master*
❯ ./node_modules/bit-docs/bin/bit-docs -f
WARNING!!
There is no @page tag. did you mean @param ?

WARNING: Unable to document  {"src":{"path":"docs/easyaspie.md"},"body":"\n```j
```

---

Error that happens if you remove `bit-docs-js`:

```
~/tmp/repro-bit-docs/super-simple-bit-docs master*
❯ ./node_modules/bit-docs/bin/bit-docs -f
/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/process/file.js:64
	var processed = siteConfig.processors.some(function(processor){
	                                     ^

TypeError: Cannot read property 'some' of undefined
    at processFile (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/process/file.js:64:39)
    at /Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/process/process.js:88:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

---

Error that happens if you remove `bit-docs-generate-html`:

```
~/tmp/repro-bit-docs/super-simple-bit-docs master*
❯ ./node_modules/bit-docs/bin/bit-docs -f
/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:155
                throw e;
                ^

TypeError: Cannot read property 'map' of undefined
    at generateOne (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/generate/generate.js:63:39)
    at generateAndWatch (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/generate/generate.js:82:10)
    at /Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/main.js:6:10
    at _fulfilled (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:796:13)
    at /Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:604:44
    at runSingle (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:137:13)
    at flush (/Users/leoj/tmp/repro-bit-docs/super-simple-bit-docs/node_modules/bit-docs/lib/configure/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

It looks like identical errors are thrown when testing against `bit-docs/bit-docs#bit-docs-bit-doced`.

Therefore, this leads me to believe those "plugins" are mandatory:

- [bit-docs-glob-finder](https://github.com/bit-docs/bit-docs-glob-finder)
- [bit-docs-dev](https://github.com/bit-docs/bit-docs-dev)
- [bit-docs-js](https://github.com/bit-docs/bit-docs-js)
- [bit-docs-generate-html](https://github.com/bit-docs/bit-docs-generate-html)

**Comment by justinbmeyer** [comment]
Those plugins aren't mandatory.  You just have to have some sort of "finder" and some sort of "generator".

**Comment by leoj3n** [comment]
Ah, okay, that makes sense.
