### ISSUE TITLE
Imports the wrong handlebars if there's already one

### ISSUE THREAD

**Issue by matthewp** [bit-docs/bit-docs#2]
If you already have a handlebars in your node_modules (such as if you have documentjs installed) it will try to use that one, instead of the one installed within bit-docs.

**Comment by leoj3n** [comment]
@matthewp You must have insight as to how to solve this one, What with your npm experience?

I will try and reproduce.

**Comment by matthewp** [comment]
Only if it doesn't explicitly depend on handlebars...

**Comment by leoj3n** [comment]
Question: Are we talking global install?

**Comment by leoj3n** [comment]
If you're talking bit-docs and documentjs in the same package.json, I can't imagine a reason you would have those in the same project. Not saying we shouldn't try and fix the issue, just that I don't understand the use case.

**Comment by leoj3n** [comment]
(accidentally closed issue)

**Comment by leoj3n** [comment]
@matthewp Can close this? Unless you still see think it's a present issue.
