### ISSUE TITLE
How should bit-docs handle plugin order?

### ISSUE THREAD

**Issue by leoj3n** [bit-docs/bit-docs#28]
http://forums.donejs.com/t/donejs-contributors-meeting-2017-04-14/598/5?u=leoj3n

**Comment by andrejewski** [comment]
[Fixpack](https://github.com/henrikjoreteg/fixpack) only sorts [certain sections](https://github.com/HenrikJoreteg/fixpack/blob/master/config.json#L17) of the `package.json` FWIW.
