### ISSUE TITLE
Throws if there's not a doc/ folder

### ISSUE THREAD

**Issue by matthewp** [bit-docs/bit-docs#3]

**Comment by leoj3n** [comment]
Are you saying it SHOULD throw, or that it it's throwing when it should not, and instead should just create the missing directory?

**Comment by chasenlehara** [comment]
It throws when it should just create the missing directory.

**Comment by leoj3n** [comment]
OK thanks @chasenlehara

**Comment by leoj3n** [comment]
I cannot reproduce this error. I tried with `bit-docs@0.0.6` (a release from before this comment was made) and `master`.

Steps I used to try and reproduce:

```
mkdir ~/tmp/repro-bit-docs && cd ~/tmp/repro-bit-docs && git clone https://github.com/leoj3n/super-simple-bit-docs && cd super-simple-bit-docs && npm install --save-dev bit-docs@0.0.6 && npm install && ./node_modules/bit-docs/bin/bit-docs
```
↳ Results in a clean build.

@matthewp Any chance you can provide some more details or steps to reproduce? Do I need to turn some flags on or something? Maybe it's specific to your setup or I'm not understanding the issue.

Thanks!

**Comment by matthewp** [comment]
This happens when using the markdown plugin, were you using that?

**Comment by leoj3n** [comment]
@matthewp Is the markdown plugin under the [`bit-docs` org](https://github.com/bit-docs)?

Hm.. Markdown plugin.. Does that let you render markdown in the generated HTML or something? Or is that like what would take a `Markdown.md` file and process it to a `docMap` to HTML?

**Comment by matthewp** [comment]
It's bit-docs-generate-readme. To recreate clone https://github.com/canjs/can-map and then try and run the docs. It should throw because doc/ doesn't exist.

**Comment by leoj3n** [comment]
Just going to put this here to tie these together:

https://github.com/bit-docs/bit-docs-generate-readme/issues/1
