### ISSUE TITLE
@font-face doesn't show up in code block

### ISSUE THREAD

**Issue by matthewp** [bit-docs/bit-docs#30]
Using:

````
```css
@font-face {
  font-family: 'something';
}
```
````

The `@font-face {` line is omitted. I'm guessing this is because bit-docs detects this as a tag.

**Comment by leoj3n** [comment]
I think I've seen `@@blah` in places, maybe that is for this reason?

**Comment by matthewp** [comment]
will try that, thanks.

**Comment by matthewp** [comment]
That did indeed fix it, thanks for the tip.  Perhaps something to document if not already done.
