### ISSUE TITLE
creating a bit-doc plugin for dash

### ISSUE THREAD

**Issue by pYr0x** [bit-docs/bit-docs#5]
if we are creating html pages for the documentation, maybe we can provide a offline documentation for dash https://kapeli.com/docsets

**Comment by justinbmeyer** [comment]
that would be great.  If someone has interest in starting on this, let me know and I'll create a repo and show them how to get started.

**Comment by pYr0x** [comment]
Do you want to have a short meetup today?

**Comment by justinbmeyer** [comment]
@pYr0x I can't meet today (I'm about to fly out for a bit of vacation).  However, I'm free Monday if you want to talk then.
