### ISSUE TITLE
Create bit-docs-tag-usage

### ISSUE THREAD

**Issue by chasenlehara** [bit-docs/bit-docs#9]
Add support for a `@usage` tag (or something similar) to automatically document how to use a package in different environments. It should produce something similar to what is created for DoneJS plugins ([example](https://github.com/donejs/donejs-number-input#usage)).

[Started from [this Slack conversation](https://bitovi.slack.com/archives/team-open-source/p1488564362009547).]

The idea is to create a `@usage can-connect` type tag that would be able to write out the basic "usage" stuff that is almost identical across all projects.

**Comment by justinbmeyer** [comment]
I think this should be a canjs thing.
